[build]
  command = "npm install && npm run build"
  publish = "dist"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"